const ELS = {
  sidebarNav: document.querySelector("#sidebar-nav"),
  allPageBtn: document.querySelector("#all-page-btn"),
  todayPageBtn: document.querySelector("#today-page-btn"),
  upcomingPageBtn: document.querySelector("#upcoming-page-btn"),
  pastPageBtn: document.querySelector("#past-page-btn"),
  addProjectModal: document.querySelector("#add-project-dialog"),
  addProjectForm: document.querySelector("#add-project-form"),
  projectTitleInput: document.querySelector("#project-title-input"),
  projectList: document.querySelector("#project-list"),
  contentNav: document.querySelector("#content-nav"),
  editProjectModal: document.querySelector("#edit-project-dialog"),
  editProjectForm: document.querySelector("#edit-project-form"),
  editProjectTitle: document.querySelector("#edit-project-title"),
  confirmEditProjectBtn: document.querySelector("#confirm-edit-project-btn"),
  deleteProjectBtn: document.querySelector("#delete-project-btn"),
  editProjectBtn: document.querySelector("#edit-project-btn"),
  addTodoBtn: document.querySelector("#add-task-btn"),
  addTodoModal: document.querySelector("#add-task-dialog"),
  confirmAddTodoBtn: document.querySelector("#confirm-add-task-btn"),
  addTodoForm: document.querySelector("#add-task-form"),
  todoTitleInput: document.querySelector("#task-title-input"),
  todoDescriptionInput: document.querySelector("#task-description-input"),
  todoDateInput: document.querySelector("#task-date-input"),
  todoPrioritySelect: document.querySelector("#task-priority-select"),
  content: document.querySelector("#content"),
  pageHeading: document.querySelector("#page-heading"),
  addTodoFormHeading: document.querySelector("#add-task-form-heading"),
  readTodoFormHeading: document.querySelector("#read-task-form-heading"),
  readTodoTitle: document.querySelector("#read-task-title"),
  readTodoDescription: document.querySelector("#read-task-description"),
  readTodoDate: document.querySelector("#read-task-date"),
  lowPriorityOption: document.querySelector("#low-priority-option"),
  mediumPriorityOption: document.querySelector("#medium-priority-option"),
  highPriorityOption: document.querySelector("#high-priority-option"),
  readTodoModal: document.querySelector("#read-task-dialog"),
  editReadTodoBtn: document.querySelector("#edit-read-task-btn"),
  readTodoForm: document.querySelector("#read-task-form"),
  readTodoPriority: document.querySelector("#read-task-priority"),
  confirmEditTodoBtn: null,
  cancelReadTodoBtn: document.querySelector("#cancel-read-task-btn"),
  cancelEditTodoBtn: null,
};

const STATE = {
  page: "All",
  startDate: null,
  endDate: null,
  todoIndex: null,
  isEditModalOpen: false,
  projectTitle: null,
  projectIndex: null,
};

export { ELS, STATE };
