const ELS = {
  allPageBtn: document.querySelector("#all-page-btn"),
  todayPageBtn: document.querySelector("#today-page-btn"),
  upcomingPageBtn: document.querySelector("#upcoming-page-btn"),
  addProjectDialog: document.querySelector("#add-project-dialog"),
  addProjectBtn: document.querySelector("#add-project-btn"),
  contentNav: document.querySelector("#content-nav"),
  addTodoBtn: document.querySelector("#add-task-btn"),
  addTodoModal: document.querySelector("#add-task-dialog"),
  confirmAddTodoBtn: document.querySelector("#confirm-add-task-btn"),
  addTodoForm: document.querySelector("#add-task-form"),
  todoTitleInput: document.querySelector("#task-title-input"),
  todoDescriptionInput: document.querySelector("#task-description-input"),
  todoDateInput: document.querySelector("#task-date-input"),
  todoPrioritySelect: document.querySelector("#task-priority-select"),
  content: document.querySelector("#content"),
  pageHeading: document.querySelector("#page-heading"),
  addTaskFormHeading: document.querySelector("#add-task-form-heading"),
  readTodoFormHeading: document.querySelector("#read-task-form-heading"),
  readTodoTitle: document.querySelector("#read-task-title"),
  readTodoDescription: document.querySelector("#read-task-description"),
  readTodoDate: document.querySelector("#read-task-date"),
  lowPriorityOption: document.querySelector("#low-priority-option"),
  mediumPriorityOption: document.querySelector("#medium-priority-option"),
  highPriorityOption: document.querySelector("#high-priority-option"),
  readTodoModal: document.querySelector("#read-task-dialog"),
  editReadTaskBtn: document.querySelector("#edit-read-task-btn"),
  readTodoForm: document.querySelector("#read-task-form"),
  readTodoPriority: document.querySelector("#read-task-priority"),
  confirmEditTodoBtn: null,
  cancelReadTaskBtn: document.querySelector("#cancel-read-task-btn"),
  cancelEditTaskBtn: null,
};

const STATE = {
  page: "All",
  startDate: null,
  endDate: null,
  isEditModalOpen: false,
};

export { ELS, STATE };
